name: technical_test_sofia
description: "Techinal Test Using Clean Architecture"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  json_annotation: ^4.8.1
  dio: ^5.4.1
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
